# Generated by Django 4.2 on 2023-05-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('stars', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(default=32)),
                ('view', models.CharField(blank=True, null=True)),
                ('room_type', models.CharField(default='Single Room')),
                ('price', models.IntegerField(default=100)),
                ('check_in_data', models.DateField(blank=True, null=True)),
                ('check_out_data', models.DateField(blank=True, null=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('private_bath', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hotel')),
            ],
            options={
                'unique_together': {('number', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='RoomFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minibar', models.BooleanField(default=False)),
                ('coffee_machine', models.BooleanField(default=False)),
                ('sofa', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('safety_deposit_box', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('wake_up_service', models.BooleanField(default=False)),
                ('socket_near_bed', models.BooleanField(default=False)),
                ('towels', models.BooleanField(default=False)),
                ('mosquito_net', models.BooleanField(default=False)),
                ('hairdryer', models.BooleanField(default=False)),
                ('wardrobe', models.BooleanField(default=False)),
                ('bathrobe', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimming_pool', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('spa_centre', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
