# Generated by Django 4.2 on 2023-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_roomfacilities_coffee_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomfacilities',
            name='coffee_machine',
            field=models.BooleanField(default=False),
        ),
    ]
