# Generated by Django 4.2 on 2023-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_roomfacilities_coffee_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(default='32m2'),
        ),
    ]
