# Generated by Django 4.2 on 2023-05-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_room_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_busy',
        ),
    ]
